import type { Lang } from "@/lib/highlight";

export interface CommandLine {
  cmd: string;
  action: "mailto" | "tel" | "link";
  href: string;
  note?: string;
}

export type FileLine = string | CommandLine;

export interface WorkspaceFile {
  id: string;
  name: string;
  badge: string;
  lang: Lang;
  folder?: string;
  lines: FileLine[];
}

export const EMAIL = "karthicnandakumar4545@gmail.com";
export const PHONE_DISPLAY = "+91 89400 51266";
export const PHONE_HREF = "tel:+918940051266";
export const GITHUB = "https://github.com/Karthic-45";
export const LINKEDIN = "https://www.linkedin.com/in/karthic45";

export const FILES: WorkspaceFile[] = [
  {
    id: "about",
    name: "about.md",
    badge: "MD",
    lang: "md",
    lines: [
      "# Karthic N",
      "> Backend Developer · Java & Spring Boot · Microservices · Generative AI",
      "",
      "I'm a backend developer specializing in **Java**, **Spring Boot**, REST APIs",
      "and microservices, with a growing focus on Generative AI integration.",
      "",
      "I design RAG-based document intelligence pipelines, secure systems with",
      "`JWT` and role-based access control, and ship production-grade software at",
      "the intersection of enterprise engineering and applied LLM technology.",
      "",
      "## Quick facts",
      "- Location — Tamil Nadu, India",
      "- Education — B.E. Computer Science, expected 2028",
      "- Role — Technical Lead, College Project Team",
      "- Focus — distributed backends + applied LLMs",
      "",
      "## Getting around",
      "- Open any file in the sidebar, or hit `Cmd/Ctrl + K`",
      "- Try the terminal below — start with `help` or `neofetch`",
    ],
  },
  {
    id: "skills",
    name: "skills.json",
    badge: "JSON",
    lang: "json",
    lines: [
      "{",
      '  "languages": ["Java", "Python", "SQL", "JavaScript", "HTML", "CSS"],',
      '  "backend": [',
      '    "Spring Boot", "Spring MVC", "Spring Security",',
      '    "Spring Data JPA", "Hibernate", "Spring Cloud", "Eureka Server"',
      "  ],",
      '  "ai_genai": ["OpenAI API", "LangChain", "RAG (FAISS)", "OCR", "FastAPI"],',
      '  "databases": ["MySQL", "PostgreSQL", "MongoDB", "Redis"],',
      '  "tools_devops": [',
      '    "Git", "GitHub Actions", "Maven", "Docker",',
      '    "Docker Compose", "Postman", "Swagger", "Linux"',
      "  ],",
      '  "cloud_messaging": ["AWS EC2", "AWS S3", "Apache Kafka"],',
      '  "concepts": [',
      '    "OOP", "Design Patterns", "JWT/RBAC", "API Gateway",',
      '    "Service Discovery", "Distributed Systems", "CI/CD"',
      "  ]",
      "}",
    ],
  },
  {
    id: "proj-intelli-credit",
    name: "intelli-credit.ts",
    badge: "TS",
    lang: "ts",
    folder: "projects",
    lines: [
      "// GenAI · FinTech",
      "export const intelliCredit = {",
      '  name: "Intelli-Credit",',
      '  tagline: "Corporate Credit Decisioning Engine",',
      '  stack: ["FastAPI", "LangChain", "FAISS", "PostgreSQL", "React", "OCR"],',
      "",
      "  highlights: [",
      '    "LLM-driven credit appraisal platform automating loan risk assessment',
      '     across financial documents, GST filings and bank statements —',
      '     cutting manual review effort by ~70%.",',
      '    "FAISS-based RAG pipeline improved document retrieval accuracy by',
      '     ~60% over traditional keyword search.",',
      '    "OCR document intelligence parsing 50+ scanned financial document',
      '     types in near real-time.",',
      '    "Automated Credit Appraisal Memo generation with LLM risk scores —',
      '     report prep dropped from hours to minutes.",',
      "  ],",
      "",
      "  impact: { manualEffort: -70, retrievalAccuracy: +60, docTypes: 50 },",
      "};",
    ],
  },
  {
    id: "proj-secure-agent",
    name: "secure-agent.ts",
    badge: "TS",
    lang: "ts",
    folder: "projects",
    lines: [
      "// Security · Platform",
      "export const secureAgent = {",
      '  name: "SecureAgent",',
      '  tagline: "Secure AI Agent Management Platform",',
      '  stack: ["Java", "Spring Boot", "Spring Security", "JWT", "MySQL"],',
      "",
      "  highlights: [",
      '    "Production-grade backend for AI agent lifecycle management —',
      '     registration, activation, monitoring and deactivation at scale.",',
      '    "Secured 20+ API endpoints with JWT auth and RBAC via Spring',
      '     Security — zero unauthorized access incidents in testing.",',
      '    "REST APIs following OpenAPI/Swagger standards, cutting frontend',
      '     integration time by ~40%.",',
      '    "Audit logging and token validation middleware for end-to-end',
      '     platform security compliance.",',
      "  ],",
      "",
      "  impact: { endpointsSecured: 20, responseTime: -35, breaches: 0 },",
      "};",
    ],
  },
  {
    id: "proj-ecommerce",
    name: "ecommerce-microservices.ts",
    badge: "TS",
    lang: "ts",
    folder: "projects",
    lines: [
      "// Distributed Systems · Microservices",
      "export const ecommercePlatform = {",
      '  name: "E-Commerce Platform",',
      '  tagline: "Monolith decomposed into deployable services",',
      '  stack: ["Spring Boot", "Spring Cloud", "Docker", "MySQL", "Eureka"],',
      "",
      '  services: ["product", "user", "order", "payment"],',
      "",
      "  highlights: [",
      '    "Decomposed a monolithic e-commerce system into independently',
      '     deployable microservices using Spring Cloud + Eureka discovery.",',
      '    "API Gateway for centralized routing, load balancing and request',
      '     filtering across 4+ services.",',
      '    "Containerized every service with Docker Compose, cutting',
      '     environment setup time by ~50%.",',
      "  ],",
      "",
      "  impact: { setupTime: -50, services: 4 },",
      "};",
    ],
  },
  {
    id: "proj-autonomous-car",
    name: "autonomous-car.py",
    badge: "PY",
    lang: "py",
    folder: "projects",
    lines: [
      "# IoT · Robotics · Computer Vision",
      "",
      "class AutonomousCar:",
      '    """Autonomous vehicle prototype — Raspberry Pi + OpenCV."""',
      "",
      '    stack = ["Raspberry Pi", "Python", "OpenCV", "IoT", "Sensors"]',
      "",
      "    def highlights(self):",
      "        return [",
      '            "Obstacle detection, real-time lane recognition and path',
      '             planning through OpenCV and multi-sensor fusion.",',
      '            "Calibrated low-latency control logic for smooth navigation.",',
      '            "Directional accuracy improved ~45% through iterative sensor',
      '             tuning and algorithm refinement.",',
      "        ]",
      "",
      "    def impact(self):",
      '        return {"directional_accuracy": 45, "latency": "low"}',
      "",
      "",
      "# >>> AutonomousCar().drive()",
      "# en route ...",
    ],
  },
  {
    id: "proj-store",
    name: "store-management.ts",
    badge: "TS",
    lang: "ts",
    folder: "projects",
    lines: [
      "// Enterprise Backend",
      "export const storeManagement = {",
      '  name: "Store Management System",',
      '  tagline: "Inventory, sales and supplier backend",',
      '  stack: ["Java", "Spring Boot", "MySQL"],',
      "",
      "  highlights: [",
      '    "Inventory, sales and supplier management services with REST APIs',
      '     for real-time stock monitoring.",',
      '    "Analytical report generation for high-volume inventory operations.",',
      '    "Spring Data JPA query tuning reduced average execution time by',
      '     ~25% on high-volume operations.",',
      "  ],",
      "",
      "  impact: { queryTime: -25 },",
      "};",
    ],
  },
  {
    id: "experience",
    name: "experience.log",
    badge: "LOG",
    lang: "log",
    lines: [
      "[2024-01-08 09:00] INFO  role_start: Technical Lead — College Project Team",
      "[2024-01-08 09:00] INFO  org: Sri Krishna College of Technology, Tamil Nadu",
      "[2024-03-10 14:22] INFO  Led a cross-functional team of 4 developers shipping",
      "                         an LLM-driven credit analysis platform.",
      "[2024-05-22 11:05] INFO  Coordinated API design, DB schema planning and",
      "                         microservices decomposition across all projects.",
      "[2024-08-14 16:40] OK    Git workflows + code review standards established —",
      "                         team delivery speed improved ~30%.",
      "[2024-11-02 10:15] INFO  Mentored juniors on Spring Boot, REST design and",
      "                         JWT-based security.",
      "[2025-02-19 13:30] OK    5+ backend and GenAI projects shipped to completion.",
      "",
      "[2028-06-01 00:00] WARN  expected_graduation: B.E. Computer Science",
      "                         Sri Krishna College of Technology — CGPA 8.0/10.0",
      "                         status: in_progress",
    ],
  },
  {
    id: "achievements",
    name: "achievements.yml",
    badge: "YML",
    lang: "yml",
    lines: [
      "# measurable outcomes",
      "metrics:",
      "  credit_analysis_turnaround_reduction: 70%",
      "  document_retrieval_accuracy_gain: 60%",
      "  api_endpoints_secured: 20",
      "  critical_vulnerabilities: 0",
      "  projects_shipped: 5",
      "  team_delivery_speed_improvement: 30%",
      "  environment_setup_time_reduction: 50%",
      "",
      "highlights:",
      "  - Applied Generative AI tooling (OpenAI, LangChain, FAISS) inside",
      "    Java-based enterprise backends.",
      "  - Zero critical vulnerabilities across the full test lifecycle.",
      "  - Guided a 4-person team with structured Git workflows and reviews.",
    ],
  },
  {
    id: "contact",
    name: "contact.sh",
    badge: "SH",
    lang: "sh",
    lines: [
      "#!/bin/bash",
      "# Let's build something worth shipping.",
      "",
      `EMAIL="${EMAIL}"`,
      `PHONE="${PHONE_DISPLAY}"`,
      "",
      "# click any line below to run it",
      {
        cmd: 'open "mailto:$EMAIL"',
        action: "mailto",
        href: `mailto:${EMAIL}`,
        note: "say hello",
      },
      {
        cmd: 'open "tel:$PHONE"',
        action: "tel",
        href: PHONE_HREF,
        note: "give me a call",
      },
      {
        cmd: 'open "github.com/Karthic-45"',
        action: "link",
        href: GITHUB,
        note: "code",
      },
      {
        cmd: 'open "linkedin.com/in/karthic45"',
        action: "link",
        href: LINKEDIN,
        note: "connect",
      },
      "",
      'echo "Open to backend engineering + applied GenAI roles."',
    ],
  },
];

export const getFile = (id: string): WorkspaceFile =>
  FILES.find((f) => f.id === id) ?? FILES[0];
